version: "3.8"

services:

  db: 
    image: postgres:latest
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=khoanguyen
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=postgres
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - db:/var/lib/postgresql/data

  api:
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=khoanguyen
      - DB_PASSWORD=abc123
      - DB_DATABASE=postgres
    ports:
      - 8000:8000
    build: 
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped

  ui: 
    build: 
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - 3000:3000
    restart: unless-stopped

# volumes:
#   db:
#     driver: local