# Specify version of Docker.
version: "3"

# Add services
services:
  # App service.
  app: 
    # Build from root folder
    build: 
      context: .
      dockerfile: Dockerfile
    # Map ports to 8000
    ports:
      - 8000:8000
    # Restart when Docker is stopped.
    restart: unless-stopped